#!/usr/bin/env python3
"""Generate the bundled skill catalog index for OMOC."""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path


OMOC_DIRECT_SKILLS = {"clonedeps", "codemap", "simplify"}


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    if not text.startswith("---\n"):
        raise ValueError("missing YAML frontmatter")

    parts = text.split("\n")
    try:
        end_index = parts[1:].index("---") + 1
    except ValueError as exc:
        raise ValueError("unterminated YAML frontmatter") from exc

    frontmatter: dict[str, str] = {}
    lines = parts[1:end_index]
    index = 0
    while index < len(lines):
        line = lines[index]
        index += 1
        if not line.strip() or line.startswith((" ", "\t")) or ":" not in line:
            continue
        key, raw_value = line.split(":", 1)
        value = raw_value.strip()
        if value in {">", "|"}:
            block: list[str] = []
            while index < len(lines):
                next_line = lines[index]
                if next_line and not next_line.startswith((" ", "\t")) and ":" in next_line:
                    break
                if next_line.strip():
                    block.append(next_line.strip())
                index += 1
            value = (" " if raw_value.strip() == ">" else "\n").join(block)
        frontmatter[key.strip()] = value.strip().strip('"\'')

    body = "\n".join(parts[end_index + 1 :])
    return frontmatter, body


def iter_skill_dirs(skills_root: Path):
    for skill_file in sorted(skills_root.rglob("SKILL.md")):
        skill_dir = skill_file.parent
        rel_parts = skill_dir.relative_to(skills_root).parts
        if any(part.startswith(".") for part in rel_parts):
            continue
        if len(rel_parts) == 1 and rel_parts[0] in OMOC_DIRECT_SKILLS:
            continue
        yield skill_dir


def build_index(root: Path) -> tuple[str, str]:
    skills_root = root / "src" / "skills"
    entries: list[dict[str, str]] = []

    for skill_dir in iter_skill_dirs(skills_root):
        skill_file = skill_dir / "SKILL.md"
        frontmatter, _ = split_frontmatter(skill_file.read_text(encoding="utf-8"))
        rel_parts = skill_dir.relative_to(skills_root).parts
        entry = {
            "name": frontmatter["name"],
            "path": "skills/" + str(skill_file.relative_to(skills_root)),
            "category": rel_parts[0],
        }
        entries.append(entry)

    categories = Counter(entry["category"] for entry in entries)
    payload = {
        "generated_by": "scripts/generate_skill_index.py",
        "summary": {
            "total_skills": len(entries),
            "categories": dict(sorted(categories.items())),
        },
        "skills": entries,
    }
    json_output = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"

    lines = [
        "# Skills Index",
        "",
        "Generated by `python3 scripts/generate_skill_index.py`.",
        "",
        "## Summary",
        "",
        f"- Total skills: {len(entries)}",
        "- Categories:",
    ]
    for category, count in sorted(categories.items()):
        lines.append(f"  - `{category}`: {count}")

    lines.extend(["", "## Skills by category"])
    grouped: dict[str, list[dict[str, str]]] = {}
    for entry in entries:
        grouped.setdefault(entry["category"], []).append(entry)

    for category in sorted(grouped):
        lines.extend(["", f"### {category}", ""])
        for entry in grouped[category]:
            lines.append(f"- `{entry['name']}` — `{entry['path']}`")

    return json_output, "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--stdout", choices=["json", "md"])
    args = parser.parse_args()

    root = Path(__file__).resolve().parent.parent
    json_output, markdown_output = build_index(root)
    json_path = root / "src" / "skills" / "index.json"
    md_path = root / "src" / "skills" / "index.md"

    if args.stdout == "json":
        print(json_output, end="")
        return 0
    if args.stdout == "md":
        print(markdown_output, end="")
        return 0

    if args.check:
        failures = []
        if not json_path.exists() or json_path.read_text(encoding="utf-8") != json_output:
            failures.append("src/skills/index.json is out of date")
        if not md_path.exists() or md_path.read_text(encoding="utf-8") != markdown_output:
            failures.append("src/skills/index.md is out of date")
        if failures:
            print("\n".join(failures))
            print("Run: python3 scripts/generate_skill_index.py")
            return 1
        print("OK: generated skill index is up to date")
        return 0

    json_path.write_text(json_output, encoding="utf-8")
    md_path.write_text(markdown_output, encoding="utf-8")
    print(f"Wrote {json_path.relative_to(root)} and {md_path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
