#!/usr/bin/env python3
"""Lightweight doctor for OMOC's bundled skill catalog."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def build_report(root: Path) -> tuple[int, dict]:
    skills_root = root / "src" / "skills"
    indexed_skills = json.loads(
        (skills_root / "index.json").read_text(encoding="utf-8"),
    )["summary"]["total_skills"]
    scripts = [
        root / "scripts" / "generate_skill_index.py",
        root / "scripts" / "validate-hub.sh",
        root / "scripts" / "audit_skills.py",
        root / "scripts" / "hub_doctor.py",
    ]
    skill_files = sorted(skills_root.rglob("SKILL.md"))
    pyc_files = sorted(
        path for path in skills_root.rglob("*") if path.name == "__pycache__" or path.suffix in {".pyc", ".pyo", ".pyd"}
    )
    missing = [str(path.relative_to(root)) for path in scripts if not path.exists()]
    failures = len(missing) + len(pyc_files)
    return failures, {
        "healthy": failures == 0,
        "skill_count": len(skill_files),
        "indexed_skill_count": indexed_skills,
        "index_json": (skills_root / "index.json").exists(),
        "index_md": (skills_root / "index.md").exists(),
        "missing_scripts": missing,
        "generated_bytecode": [str(path.relative_to(root)) for path in pyc_files],
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    failures, report = build_report(root)
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print("OMOC skill catalog doctor")
        print(f"skills: {report['skill_count']}")
        print(f"index.json: {'yes' if report['index_json'] else 'no'}")
        print(f"index.md: {'yes' if report['index_md'] else 'no'}")
        if report["missing_scripts"]:
            print("missing scripts:")
            for item in report["missing_scripts"]:
                print(f"- {item}")
        if report["generated_bytecode"]:
            print("generated bytecode:")
            for item in report["generated_bytecode"]:
                print(f"- {item}")
        print("healthy" if report["healthy"] else "issues found")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
