#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

echo "[1/4] Validate generated skill index"
python3 scripts/generate_skill_index.py --check

echo "[2/4] Validate skill frontmatter"
python3 - <<'PY'
from pathlib import Path

root = Path.cwd()
errors = []
for skill in sorted((root / "src" / "skills").rglob("SKILL.md")):
    text = skill.read_text(encoding="utf-8", errors="ignore")
    if not text.startswith("---\n"):
        errors.append(f"{skill}: missing frontmatter")
        continue
    head = text.split("---", 2)[1]
    name = None
    description = None
    for line in head.splitlines():
        if line.startswith("name:"):
            name = line.split(":", 1)[1].strip().strip('"\'')
        if line.startswith("description:"):
            description = line.split(":", 1)[1].strip().strip('"\'')
    if not name:
        errors.append(f"{skill}: missing name")
    if description in {None, ""}:
        errors.append(f"{skill}: missing description")

if errors:
    print("\n".join(errors))
    raise SystemExit(1)
print("OK: skill frontmatter present")
PY

echo "[3/4] Validate Python syntax"
python3 - <<'PY'
import py_compile
from pathlib import Path

root = Path.cwd()
for file in sorted(root.rglob("*.py")):
    if any(part in {".git", "node_modules", "dist"} for part in file.parts):
        continue
    py_compile.compile(str(file), doraise=True)
print("OK: Python syntax")
PY

echo "[4/4] Validate no generated bytecode"
find "$ROOT_DIR" -type d -name "__pycache__" -prune -exec rm -rf {} +
python3 - <<'PY'
from pathlib import Path

root = Path.cwd()
bad = [p for p in root.rglob("*") if p.name == "__pycache__" or p.suffix in {".pyc", ".pyo", ".pyd"}]
if bad:
    print("Forbidden generated files:")
    for path in bad:
        print(path)
    raise SystemExit(1)
print("OK: no generated Python bytecode")
PY

echo "All skill catalog validations passed"
