import providerAssignmentGuide from '../cli/provider-assignment-guide.json';
import {
  BOARD_AGENT_MODEL_TIERS,
  type BoardAgentTier,
  type BoardAgentTierModels,
} from '../cli/providers';
import type { CustomAgentDefinition } from './custom-definitions';

const CUSTOM_AGENT_SCHEMA_URL =
  'https://unpkg.com/blacktower@latest/custom-agent.schema.json';

// ── Tier assignments ──────────────────────────────────────────────────────────
// coding = language/tech agents that write & review code
// heavy  = complex reasoning, architecture, ops, creative
// light  = content, marketing, simple advisory
export const BOARD_AGENT_TIERS =
  providerAssignmentGuide.boardAgentTiers as Record<string, BoardAgentTier>;

const BOARD_AGENT_MODEL_OVERRIDES =
  providerAssignmentGuide.boardAgentModelOverrides as Record<
    string,
    Record<string, string>
  >;

export function getBoardAgentModel(
  agentName: string,
  tiers: BoardAgentTierModels,
  overrides: Record<string, string> = {},
): string {
  const override = overrides[agentName];
  if (override) return override;

  const tier = BOARD_AGENT_TIERS[agentName] ?? 'heavy';
  return tiers[tier];
}

export function getBoardAgentDefinitions(
  boardProvider?: string,
): readonly CustomAgentDefinition[] {
  if (!boardProvider) return DEFAULT_BOARD_AGENT_DEFINITIONS;
  const tiers = BOARD_AGENT_MODEL_TIERS[boardProvider];
  if (!tiers) return DEFAULT_BOARD_AGENT_DEFINITIONS;
  const overrides = BOARD_AGENT_MODEL_OVERRIDES[boardProvider] ?? {};
  return DEFAULT_BOARD_AGENT_DEFINITIONS.map((def) => ({
    ...def,
    model: getBoardAgentModel(def.name, tiers, overrides),
  }));
}

export interface DefaultBoardAgentGroup {
  title: 'BUILD' | 'OPS' | 'GROWTH' | 'PRODUCT' | 'MYTH';
  glyph: string;
  names: readonly string[];
}

export const DEFAULT_BOARD_AGENT_GROUPS = [
  {
    title: 'BUILD',
    glyph: '◆',
    names: [
      'backend-architect',
      'go-advisor',
      'python-advisor',
      'rust-advisor',
      'typescript-advisor',
      'qa-test-advisor',
    ],
  },
  {
    title: 'OPS',
    glyph: '◍',
    names: [
      'cloud-devops-advisor',
      'database-advisor',
      'observability-advisor',
      'ops-sre-advisor',
      'security-advisor',
    ],
  },
  {
    title: 'GROWTH',
    glyph: '✹',
    names: [
      'content-strategist',
      'copy-chief',
      'cro-strategist',
      'launch-strategist',
      'seo-strategist',
      'social-media-strategist',
    ],
  },
  {
    title: 'PRODUCT',
    glyph: '◇',
    names: [
      'agent-systems-architect',
      'devtools-product-advisor',
      'dx-documentation-advisor',
      'maintainer-strategy-advisor',
    ],
  },
  {
    title: 'MYTH',
    glyph: '✶',
    names: [
      'docs-advisor',
      'media-producer',
      'story-editor',
      'subcult-creative-director',
      'worldbuilder',
    ],
  },
] satisfies readonly DefaultBoardAgentGroup[];

export const DEFAULT_BOARD_AGENT_NAMES = DEFAULT_BOARD_AGENT_GROUPS.flatMap(
  (group) => group.names,
) satisfies readonly string[];

export const DEFAULT_BOARD_AGENT_DEFINITIONS = [
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'backend-architect',
    displayName: 'api-forge',
    model: 'openai/gpt-5.5',
    variant: 'high',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'architecture-patterns',
      'api-design-principles',
      'auth-implementation-patterns',
      'nodejs-backend-patterns',
      'workflow-orchestration-patterns',
      'cqrs-implementation',
      'openapi-spec-generation',
      'websocket-engineer',
      'stripe-integration',
      'cli-developer',
      'develop-userscripts',
      'python-design-patterns',
      'python-type-safety',
      'javascript-pro',
      'typescript-pro',
      'design-an-interface',
    ],
    mcps: ['*'],
    prompt:
      'You are Backend Architect. Advise on API shape, service boundaries, auth, workflows, and backend maintainability. Prefer concise recommendations, risks, and file references. Do not implement unless explicitly asked.',
    orchestratorPrompt:
      "@backend-architect\n- Role: Backend architecture advisor for API design, auth boundaries, service decomposition, orchestration, and maintainability tradeoffs\n- Delegate when: backend architecture is unclear • API contract design matters • auth/session/RBAC boundaries matter • service/workflow design has long-term cost\n- Don't delegate when: change is a small implementation detail • UI-only task • docs-only task",
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'cloud-devops-advisor',
    displayName: 'cloud-runner',
    model: 'openai/gpt-5.5',
    variant: 'medium',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'cloudflare-deploy',
      'deployment-pipeline-design',
      'secure-linux-web-hosting',
      'terraform-module-library',
      'k8s-manifest-generator',
      'helm-chart-scaffolding',
      'prometheus-configuration',
      'grafana-dashboards',
      'slo-implementation',
      'secrets-management',
      'k8s-security-policies',
      'design-an-interface',
    ],
    mcps: ['*'],
    prompt:
      'You are Cloud DevOps Advisor. Advise on deployment, hosting, CI/CD, Cloudflare, Vercel, Linux hardening, and Terraform. Prioritize reversible, secure rollout steps.',
    orchestratorPrompt: `@cloud-devops-advisor\n- Role: Cloud/devops advisor for deploy, hosting, CI/CD, infra, and rollback planning\n- Delegate when: deployment, hosting, DNS, CI/CD, or infra changes are requested\n- Don't delegate when: local app code only`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'content-strategist',
    displayName: 'signal-planner',
    model: 'openai/gpt-5.4-mini',
    variant: 'high',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'content-strategy',
      'seo-audit',
      'ai-seo',
      'programmatic-seo',
      'schema-markup',
      'copywriting',
      'customer-research',
      'competitive-landscape',
      'competitor-profiling',
      'social-content',
      'launch-strategy',
      'email-sequence',
      'book-marketing',
      'summarization',
    ],
    mcps: ['*'],
    prompt:
      'You are Content Strategist. Plan content strategy, topic clusters, editorial calendars, SEO/AI visibility, distribution, repurposing, and content production systems.',
    orchestratorPrompt: `@content-strategist\n- Role: Content planning advisor for strategy, topic clusters, editorial calendars, SEO/AI search, distribution, and repurposing\n- Delegate when: content roadmap, topics, blog strategy, pSEO, AI SEO, content calendar, or content system design matters\n- Don't delegate when: single social post only; use social-media-strategist`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'copy-chief',
    displayName: 'copy-sigil',
    model: 'openai/gpt-5.5',
    variant: 'medium',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'copywriting',
      'email-sequence',
      'sales-enablement',
      'subcult-brand-voice',
      'humanizer',
      'prose-style',
      'voice-analysis',
      'marketing-psychology',
      'content-strategy',
      'book-marketing',
      'social-content',
      'edit-article',
      'writing-beats',
      'writing-fragments',
      'writing-shape',
    ],
    mcps: ['*'],
    prompt:
      'You are Copy Chief. Write and critique marketing copy, email, sales enablement, and brand voice. Make copy specific, persuasive, and non-generic.',
    orchestratorPrompt: `@copy-chief\n- Role: Marketing copy advisor/writer for web pages, email, sales materials, and brand voice\n- Delegate when: copy quality, messaging, CTA, positioning, or sales collateral is central\n- Don't delegate when: copy is incidental`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'cro-strategist',
    displayName: 'conversion-alchemist',
    model: 'openai/gpt-5.4-mini',
    variant: 'high',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'page-cro',
      'copywriting',
      'customer-research',
      'marketing-psychology',
      'ab-test-setup',
      'launch-strategy',
      'email-sequence',
      'social-content',
      'paid-ads',
      'web-design-reviewer',
      'design-an-interface',
    ],
    mcps: ['*'],
    prompt:
      'You are CRO Strategist. Diagnose conversion friction, signup/paywall/form issues, and page messaging. Recommend testable improvements.',
    orchestratorPrompt: `@cro-strategist\n- Role: Conversion advisor for landing pages, signup, forms, paywalls, and activation friction\n- Delegate when: conversions, bounce, signup, pricing-page, or funnel friction matters\n- Don't delegate when: no user conversion path exists`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'database-advisor',
    displayName: 'data-vault',
    model: 'openai/gpt-5.5',
    variant: 'high',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'postgres-pro',
      'hybrid-search-implementation',
      'data-quality-frameworks',
      'database-migration',
      'gdpr-data-handling',
      'python-resource-management',
      'python-performance-optimization',
      'rag-implementation',
    ],
    mcps: ['*'],
    prompt:
      'You are Database Advisor. Advise on PostgreSQL, schema design, query/index performance, data quality, dbt, and vector/hybrid search. Return concrete risks and migration-safe recommendations.',
    orchestratorPrompt: `@database-advisor\n- Role: Database/search advisor for PostgreSQL, schema, query optimization, dbt, data quality, vector and hybrid search\n- Delegate when: DB schema/index/search/RAG/data quality decisions affect correctness or performance\n- Don't delegate when: no persistence/search/data concerns`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'docs-advisor',
    displayName: 'doc-scribe',
    model: 'openai/gpt-5.4-mini',
    variant: 'high',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'doc',
      'pdf',
      'pptx-generator',
      'spreadsheet',
      'review-doc-consistency',
      'hads',
      'readme-i18n',
      'summarization',
      'fact-check',
      'humanizer',
      'copywriting',
      'obsidian-vault',
      'edit-article',
      'writing-beats',
      'writing-fragments',
      'writing-shape',
    ],
    mcps: ['*'],
    prompt:
      'You are Docs Advisor. Create, edit, and review documentation and document artifacts, including DOCX, PDF, PPTX, spreadsheets, READMEs, HADS docs, and docs-vs-code consistency.',
    orchestratorPrompt: `@docs-advisor\n- Role: Documentation and artifact advisor for docs, PDFs, slide decks, spreadsheets, READMEs, and consistency checks\n- Delegate when: document creation/editing/review, docs consistency, README/localization, or artifact formatting matters\n- Don't delegate when: external library lookup only; use librarian`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'go-advisor',
    displayName: 'go-runner',
    model: 'openai/gpt-5.5',
    variant: 'high',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'golang-pro',
      'api-design-principles',
      'architecture-patterns',
      'tdd',
      'security-best-practices',
      'design-an-interface',
    ],
    mcps: ['*'],
    prompt:
      'You are Go Advisor. Advise on idiomatic Go, concurrency, goroutines/channels, interfaces, generics, microservices, tests, benchmarks, and performance.',
    orchestratorPrompt: `@go-advisor\n- Role: Go advisor for idiomatic Go, concurrency, services, tests, benchmarks, and performance\n- Delegate when: Go code, goroutines/channels, Go APIs, tests, or Go performance matters\n- Don't delegate when: non-Go work`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'launch-strategist',
    displayName: 'launch-seer',
    model: 'openai/gpt-5.4-mini',
    variant: 'medium',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'launch-strategy',
      'content-strategy',
      'customer-research',
      'paid-ads',
      'email-sequence',
      'ab-test-setup',
      'social-content',
      'competitor-profiling',
      'competitor-alternatives',
      'sales-enablement',
      'copywriting',
      'marketing-psychology',
    ],
    mcps: ['*'],
    prompt:
      'You are Launch Strategist. Plan launches, announcements, directory pushes, email sequences, and channel sequencing. Keep output practical and execution-ready.',
    orchestratorPrompt: `@launch-strategist\n- Role: Launch and acquisition advisor for GTM, directories, email, paid, and channel sequencing\n- Delegate when: launch, announcement, campaign, or acquisition planning is requested\n- Don't delegate when: pure code task`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'media-producer',
    displayName: 'media-signal',
    model: 'openai/gpt-5.4-mini',
    variant: 'medium',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'video',
      'image',
      'presentation-design',
      'ebook-analysis',
      'musical-dna',
      'humanizer',
      'subcult-brand-voice',
      'subcult-visual-design',
      'subcult-worldbuilding',
      'pdf',
      'pptx-generator',
      'edit-article',
      'writing-beats',
      'writing-fragments',
      'writing-shape',
    ],
    mcps: ['*'],
    prompt:
      'You are Media Producer. Advise on image, video, slide, music-description, and ebook-analysis workflows. Keep specs production-ready.',
    orchestratorPrompt: `@media-producer\n- Role: Creative media advisor for images, video, slide decks, music prompts, and ebook analysis\n- Delegate when: visual/media/presentation generation or analysis is requested\n- Don't delegate when: code-only task`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'observability-advisor',
    displayName: 'system-watch',
    model: 'openai/gpt-5.5',
    variant: 'high',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'grafana-dashboards',
      'prometheus-configuration',
      'slo-implementation',
      'distributed-tracing',
      'python-observability',
      'sast-configuration',
      'design-an-interface',
    ],
    mcps: ['*'],
    prompt:
      'You are Observability Advisor. Advise on logs, metrics, traces, dashboards, alerts, SLIs/SLOs, incident debugging, and production signal quality.',
    orchestratorPrompt: `@observability-advisor\n- Role: Observability advisor for logs, metrics, traces, dashboards, alerts, and SLOs\n- Delegate when: production debugging, monitoring, tracing, alerting, dashboards, or signal quality matters\n- Don't delegate when: deploy mechanics without observability concern; use cloud/ops`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'ops-sre-advisor',
    displayName: 'uptime-warden',
    model: 'openai/gpt-5.5',
    variant: 'high',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'slo-implementation',
      'prometheus-configuration',
      'grafana-dashboards',
      'distributed-tracing',
      'deployment-pipeline-design',
      'secure-linux-web-hosting',
      'terraform-module-library',
      'k8s-manifest-generator',
      'helm-chart-scaffolding',
      'secrets-management',
      'python-observability',
    ],
    mcps: ['*'],
    prompt:
      'You are Ops/SRE Advisor. Advise on reliability, monitoring, alerting, deploy safety, rollbacks, incidents, SLOs, traces, dashboards, and operational risk. Prefer reversible, observable plans.',
    orchestratorPrompt: `@ops-sre-advisor\n- Role: Ops/SRE advisor for reliability, incidents, deploy safety, observability, SLOs, and runbooks\n- Delegate when: uptime, production risk, monitoring, alerts, incidents, rollback, or operational readiness matters\n- Don't delegate when: local-only code change without runtime/ops concern`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'python-advisor',
    displayName: 'python-mage',
    model: 'openai/gpt-5.5',
    variant: 'high',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'async-python-patterns',
      'python-anti-patterns',
      'python-background-jobs',
      'python-code-style',
      'python-configuration',
      'python-design-patterns',
      'python-error-handling',
      'python-observability',
      'python-packaging',
      'python-performance-optimization',
      'python-project-structure',
      'python-resilience',
      'python-resource-management',
      'python-testing-patterns',
      'python-type-safety',
      'uv-package-manager',
      'temporal-python-testing',
      'postgres-pro',
      'design-an-interface',
    ],
    mcps: ['*'],
    prompt:
      'You are Python Advisor. Advise on Python architecture, async, packaging, typing, testing, config, observability, performance, resilience, resources, and idiomatic maintainability.',
    orchestratorPrompt: `@python-advisor\n- Role: Python advisor for architecture, async, tests, typing, packaging, config, observability, performance, and resilience\n- Delegate when: Python code quality, Python service design, pytest, uv, async, typing, or Python performance matters\n- Don't delegate when: non-Python work`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'qa-test-advisor',
    displayName: 'test-warden',
    model: 'openai/gpt-5.4-mini',
    variant: 'high',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'tdd',
      'webapp-testing',
      'scoutqa-test',
      'playwright',
      'temporal-python-testing',
      'backtesting-frameworks',
      'shellcheck-configuration',
      'bats-testing-patterns',
      'python-testing-patterns',
      'wcag-audit-patterns',
      'screen-reader-testing',
      'javascript-pro',
      'typescript-pro',
      'review-react-best-practices',
      'design-an-interface',
    ],
    mcps: ['*'],
    prompt:
      'You are QA Test Advisor. Design focused unit, integration, and browser test strategy. Prefer minimal tests that catch regressions and fit existing conventions.',
    orchestratorPrompt: `@qa-test-advisor\n- Role: Test strategy advisor for TDD, unit/integration/e2e coverage, and regression risk\n- Delegate when: tests are missing/unclear/flaky or a feature needs verification design\n- Don't delegate when: simply running known tests`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'rust-advisor',
    displayName: 'rust-forge',
    model: 'openai/gpt-5.5',
    variant: 'high',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'rust-pro',
      'security-best-practices',
      'refactor',
      'simplify',
      'tdd',
      'design-an-interface',
    ],
    mcps: ['*'],
    prompt:
      'You are Rust Advisor. Advise on Rust ownership, async, concurrency, memory safety, error handling, performance, and idiomatic crate structure. Return concrete risks, safer designs, and testable recommendations.',
    orchestratorPrompt: `@rust-advisor\n- Role: Rust advisor for ownership, async Rust, memory safety, Tokio/concurrency, and idiomatic systems design\n- Delegate when: Rust code, async/concurrency, unsafe/memory-safety, crate architecture, or Rust performance matters\n- Don't delegate when: no Rust code or systems-level concern`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'security-advisor',
    displayName: 'security-warden',
    model: 'openai/gpt-5.5',
    variant: 'high',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'security-threat-model',
      'security-best-practices',
      'secrets-management',
      'sast-configuration',
      'mtls-configuration',
      'k8s-security-policies',
      'secure-linux-web-hosting',
      'pci-compliance',
      'security-ownership-map',
      'memory-forensics',
      'solidity-security',
      'bash-defensive-patterns',
      'gdpr-data-handling',
      'auth-implementation-patterns',
      'stripe-integration',
    ],
    mcps: ['*'],
    prompt:
      'You are Security Advisor. Threat-model changes, identify abuse paths, and recommend pragmatic mitigations. Keep findings severity-ranked and actionable.',
    orchestratorPrompt: `@security-advisor\n- Role: Security advisor for threat models, secrets, SAST, auth abuse paths, and secure defaults\n- Delegate when: security-sensitive files, auth, secrets, data exposure, payments, or deployment boundaries are involved\n- Don't delegate when: purely cosmetic or local-only edits`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'seo-strategist',
    displayName: 'search-beacon',
    model: 'openai/gpt-5.4-mini',
    variant: 'high',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'seo-audit',
      'programmatic-seo',
      'schema-markup',
      'ai-seo',
      'content-strategy',
      'copywriting',
      'customer-research',
      'competitive-landscape',
      'competitor-alternatives',
      'competitor-profiling',
      'edit-article',
      'writing-beats',
      'writing-fragments',
      'writing-shape',
    ],
    mcps: ['*'],
    prompt:
      'You are SEO Strategist. Advise on technical SEO, programmatic SEO, schema, AI search visibility, and content architecture. Return prioritized actions.',
    orchestratorPrompt: `@seo-strategist\n- Role: SEO and AI-search advisor for technical SEO, pSEO, schema, content architecture, and visibility\n- Delegate when: SEO, rankings, search traffic, schema, llms.txt, or content strategy is requested\n- Don't delegate when: non-marketing implementation only`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'social-media-strategist',
    displayName: 'social-signal',
    model: 'openai/gpt-5.4-mini',
    variant: 'medium',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'social-content',
      'content-strategy',
      'copywriting',
      'marketing-psychology',
      'customer-research',
      'launch-strategy',
      'paid-ads',
      'image',
      'video',
      'humanizer',
      'subcult-brand-voice',
      'edit-article',
      'writing-beats',
      'writing-fragments',
      'writing-shape',
    ],
    mcps: ['*'],
    prompt:
      'You are Social Media Strategist. Plan and create social content across LinkedIn, X/Twitter, Instagram, TikTok, short-form video, hooks, calendars, repurposing, and engagement loops.',
    orchestratorPrompt: `@social-media-strategist\n- Role: Social media advisor for posts, threads, calendars, short-form video, repurposing, hooks, and engagement strategy\n- Delegate when: social platform content, social growth, content calendars, threads, reels/shorts, or post optimization matters\n- Don't delegate when: broad SEO/content architecture only; use content strategist`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'agent-systems-architect',
    displayName: 'agent-architect',
    model: 'openai/gpt-5.5',
    variant: 'high',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'blacktower',
      'plugin-integrator',
      'session-warden',
      'failure-anthropologist',
      'llm-evaluation',
      'mcp-builder',
      'prompt-craft',
      'design-an-interface',
      'workflow-orchestration-patterns',
      'architecture-patterns',
      'api-design-principles',
    ],
    mcps: ['*'],
    prompt:
      'You are Agent Systems Architect. Advise on multi-agent orchestration, delegation boundaries, autonomy, prompt/tool contracts, evaluation loops, session lifecycle risk, and agent coordination. Challenge over-agenting and under-specified tool contracts.',
    orchestratorPrompt: `@agent-systems-architect\n- Role: Agent-systems advisor for multi-agent orchestration, delegation contracts, autonomy boundaries, prompt/tool interfaces, and evaluation loops\n- Delegate when: agent architecture, specialist routing, background delegation, prompt/tool contracts, or orchestration strategy has long-term impact\n- Don't delegate when: implementing a routine local code change or writing a one-off prompt`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'devtools-product-advisor',
    displayName: 'devtools-seer',
    model: 'openai/gpt-5.4-mini',
    variant: 'high',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'blacktower',
      'control-surface-designer',
      'customer-research',
      'competitive-landscape',
      'page-cro',
      'copywriting',
      'web-design-reviewer',
      'frontend-design',
      'design-an-interface',
    ],
    mcps: ['*'],
    prompt:
      'You are Devtools Product Advisor. Advise on developer-tool workflows, feature scope, onboarding friction, user trust, control surfaces, automation boundaries, and product tradeoffs. Prefer crisp product decisions over feature accumulation.',
    orchestratorPrompt: `@devtools-product-advisor\n- Role: Developer-tools product advisor for workflow design, user trust, automation boundaries, onboarding friction, and control-surface product decisions\n- Delegate when: deciding what Blacktower/OpenCode workflow to expose, automate, simplify, or deprecate\n- Don't delegate when: the task is pure implementation with settled product behavior`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'dx-documentation-advisor',
    displayName: 'dx-scribe',
    model: 'openai/gpt-5.4-mini',
    variant: 'high',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'blacktower',
      'customize-opencode',
      'plugin-integrator',
      'release-engineer',
      'doc',
      'review-doc-consistency',
      'hads',
      'readme-i18n',
      'summarization',
      'humanizer',
      'copywriting',
    ],
    mcps: ['*'],
    prompt:
      'You are DX Documentation Advisor. Advise on install friction, configuration ergonomics, CLI/help text, error messages, README/docs structure, migration notes, and developer onboarding. Optimize for users succeeding without private maintainer context.',
    orchestratorPrompt: `@dx-documentation-advisor\n- Role: Developer-experience documentation advisor for install/config ergonomics, error messages, CLI help, onboarding, README structure, and migration notes\n- Delegate when: docs, config UX, setup instructions, or user-facing errors affect developer success\n- Don't delegate when: documentation is incidental and behavior is not user-facing`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'maintainer-strategy-advisor',
    displayName: 'maintainer-oracle',
    model: 'openai/gpt-5.5',
    variant: 'high',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'release-engineer',
      'failure-anthropologist',
      'codemod-surgeon',
      'dependency-upgrade',
      'changelog-automation',
      'opensource-guide-coach',
      'github-pro',
      'git-advanced-workflows',
      'review-doc-consistency',
      'security-ownership-map',
    ],
    mcps: ['*'],
    prompt:
      'You are Maintainer Strategy Advisor. Advise on versioning, compatibility promises, deprecations, release trains, migration paths, contributor workflow, support burden, and long-term project maintenance. Prefer sustainable maintenance over flashy changes.',
    orchestratorPrompt: `@maintainer-strategy-advisor\n- Role: Maintainer strategy advisor for versioning, deprecation policy, migration paths, compatibility promises, release cadence, and support burden\n- Delegate when: a change affects long-term maintenance, public behavior, releases, migration risk, or project governance\n- Don't delegate when: the task is a small internal fix with no compatibility or maintenance tradeoff`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'story-editor',
    displayName: 'story-scribe',
    model: 'openai/gpt-5.5',
    variant: 'medium',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'story-sense',
      'revision',
      'dialogue',
      'prose-style',
      'voice-analysis',
      'chapter-drafter',
      'drafting',
      'fact-check',
      'sensitivity-check',
      'genre-conventions',
      'character-arc',
      'story-coach',
      'story-collaborator',
      'story-idea-generator',
      'reverse-outliner',
      'edit-article',
      'writing-beats',
      'writing-fragments',
      'writing-shape',
    ],
    mcps: ['*'],
    prompt:
      'You are Story Editor. Diagnose narrative, structure, character, dialogue, prose, and revision issues. Ask before generating prose unless collaboration is requested.',
    orchestratorPrompt: `@story-editor\n- Role: Story and prose advisor for narrative diagnosis, revision, dialogue, voice, and structure\n- Delegate when: story, prose, dialogue, revision, or writing craft is requested\n- Don't delegate when: marketing copy or code task`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'subcult-creative-director',
    displayName: 'culture-oracle',
    model: 'openai/gpt-5.5',
    variant: 'medium',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'subcult-brand-voice',
      'subcult-visual-design',
      'subcult-worldbuilding',
      'image',
      'video',
      'presentation-design',
      'musical-dna',
      'humanizer',
      'frontend-design',
      'web-design-reviewer',
      'naming',
      'copywriting',
    ],
    mcps: ['*'],
    prompt:
      'You are SUBCULT Creative Director. Apply SUBCULT brand voice, visual aesthetics, and mythic/worldbuilding layer across copy, UI, naming, and artifacts.',
    orchestratorPrompt: `@subcult-creative-director\n- Role: SUBCULT creative director for brand voice, visual style, naming, and mythic world layer\n- Delegate when: SUBCULT, Patchwork, clpr.tv, subcorp, brand voice, visual identity, or lore is involved\n- Don't delegate when: generic product or code work without SUBCULT context`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'typescript-advisor',
    displayName: 'type-scribe',
    model: 'openai/gpt-5.5',
    variant: 'high',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'typescript-pro',
      'javascript-pro',
      'nodejs-backend-patterns',
      'nextjs-app-router-patterns',
      'react-modernization',
      'react-state-management',
      'review-react-best-practices',
      'web-component-design',
      'tdd',
      'webapp-testing',
      'design-an-interface',
    ],
    mcps: ['*'],
    prompt:
      'You are TypeScript Advisor. Advise on TypeScript type design, JS/TS runtime correctness, Node, React/Next, state management, tests, and maintainable app architecture.',
    orchestratorPrompt: `@typescript-advisor\n- Role: TypeScript advisor for type systems, JS/TS apps, Node, React/Next, tests, and maintainable frontend/backend TS architecture\n- Delegate when: TypeScript types, JS/TS correctness, React/Next, Node, or TS tests matter\n- Don't delegate when: non-JS/TS work`,
  },
  {
    $schema: CUSTOM_AGENT_SCHEMA_URL,
    name: 'worldbuilder',
    displayName: 'world-forge',
    model: 'openai/gpt-5.5',
    variant: 'medium',
    skills: [
      'agent-browser',
      'use-my-browser',
      'screenshot',
      'web-search',
      'caveman',
      'make-repo-contribution',
      'context-engineer',
      'deep-research',
      'systematic-debugging',
      'review-quality',
      'writing-plans',
      'grill-me',
      'grill-with-docs',
      'prototype',
      'qa',
      'request-refactor-plan',
      'teach',
      'to-issues',
      'to-prd',
      'ubiquitous-language',
      'zoom-out',
      'worldbuilding',
      'shared-world',
      'world-fates',
      'naming',
      'conlang',
      'language-evolution',
      'dna-extraction',
      'adaptation-synthesis',
      'cliche-transcendence',
      'statistical-distance',
      'list-builder',
      'game-facilitator',
      'interactive-fiction',
      'technology-impact',
      'writing-beats',
      'writing-fragments',
      'writing-shape',
    ],
    mcps: ['*'],
    prompt:
      'You are Worldbuilder. Design worlds, institutions, cultures, names, shared-world continuity, and systemic consequences. Prefer causal depth over lore dumps.',
    orchestratorPrompt: `@worldbuilder\n- Role: Worldbuilding advisor for settings, institutions, cultures, names, continuity, and systemic consequences\n- Delegate when: fictional worlds, settings, names, cultures, or lore systems matter\n- Don't delegate when: non-fiction product/domain architecture`,
  },
] satisfies readonly CustomAgentDefinition[];
